jobs:

- job: Android
  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: 'src/android-signing/unsigned.apk'
      configuration: '$(buildConfiguration)'

  - task: CopyFiles@2
    inputs:
      Contents: 'src/android-signing/unsigned.apk'
      TargetFolder: 'android-signing-APKs'
      CleanTargetFolder: true

  - task: AndroidSigning@2
    inputs:
      apkFiles: 'android-signing-APKs/unsigned.apk'
      jarsignerKeystoreFile: 'src/android-signing/keystorefile.keystore'
      jarsignerKeystorePassword: 'keystorepassword'
      jarsignerKeystoreAlias: 'alias_name'
      jarsignerKeyPassword: 'keypassword'
      zipalign: false

  - task: CopyFiles@2
    inputs:
      Contents: 'src/android-signing/unsigned.apk'
      TargetFolder: 'android-signing-APKs'
      CleanTargetFolder: true

  - task: AndroidSigning@3
    inputs:
      apkFiles: 'android-signing-APKs/unsigned.apk'
      apksignerKeystoreFile: 'src/android-signing/keystorefile.keystore'
      apksignerKeystorePassword: 'keystorepassword'
      apksignerKeystoreAlias: 'alias_name'
      apksignerKeyPassword: 'keypassword'
      apksignerArguments: 
      zipalign: false
    